@startuml Get Active Events

title Sequence: Get Active Events

actor User
participant Gateway
participant App [
    <<Container>>
    Betting Service
]
participant Database [
    <<Database>>
    SQLite
]

User -> Gateway: GET /api/v1/events
activate Gateway
Gateway -> App: GET /api/v1/events
activate App

App -> App: Handler.GetActiveEvents()
activate App #LightBlue
App -> App: Service.GetActiveEvents()
activate App #CornflowerBlue
App -> App: UseCase.GetActiveEvents()
activate App #DarkSeaGreen
App -> App: Repository.FindActiveEvents()
activate App #IndianRed
App -> Database: SELECT ... FROM events WHERE is_active=1 AND event_end_date > NOW()
activate Database
Database --> App: Rows (Active Events)
deactivate Database
App --> App: []data.Event
deactivate App #IndianRed
App --> App: []data.Event
deactivate App #DarkSeaGreen
App --> App: []data.Event
deactivate App #CornflowerBlue
App -> App: MapEventsToDTOs()
App --> Gateway: 200 OK (EventDTO List)
deactivate App #LightBlue
deactivate App
Gateway --> User: 200 OK (EventDTO List)
deactivate Gateway

@enduml