version: '3.8' # Just to be safe

services:
  migrate:
    build: 
      context: .
      dockerfile: Dockerfile
      target: builder        
    container_name: betting_migration
    networks:
      - betting_network
    volumes:
      - .:/app
      - ./data:/app/data 
    working_dir: /app 
    command: ["go", "run", "./cmd/migrate/main.go", "-dbpath", "/app/data/events.db", "-path", "./migrations", "-direction", "up"]

  app:
    build: . 
    container_name: betting_service
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      GIN_MODE: release
      HTTP_PORT: "8080"
      DB_PATH: "/app/data/events.db"
      PAYOUT_SVC_URL: "http://host.docker.internal:8081"
      PAYOUT_SVC_TIMEOUT: "5s"
      EVENT_SOURCE_URL: "https://arlan-api.azurewebsites.net" 
      EVENT_SOURCE_TIMEOUT: "15s"
      EVENT_SYNC_INTERVAL: "1m"
      CONFIG_PATH: "/app/config.yaml" 
    volumes:
      - ./data:/app/data
    networks:
      - betting_network
    depends_on:
      migrate:
        condition: service_completed_successfully

networks:
  betting_network:
    driver: bridge